### ISSUE TITLE
Basic Features

### ISSUE THREAD

**Issue by huming0618** [huming0618/codetower#5]
- build the note in tree-view
  - create the node
  - use the tab key and ctrl+tab to control the indent of the node
  - editing
  - drag & drop the node
- mark the selection and write down the note
- code-mining
  - draw the note 
  - share the note 
  - show the note from others

**Comment by huming0618** [comment]
- [ ] Feature - Add the note-node by drag and drop the selection

1. when drop into existing node, then add the mapping of the node and the selection
2. when drop to empty gap between nodes, create a new node with default name and then add the maping

**Comment by huming0618** [comment]
[Log]
try to add the mixin for tree-view
https://github.com/huming0618/codetower/commit/8e7a7693c4cf414842f47ec46f5815b69a9d3d40

- [x] testing the tree-view mixin https://github.com/huming0618/codetower/commit/aa0cdb83cd843bba70197e596706cc320fdf5260
- [x] code-tree with the mixin tree-view https://github.com/huming0618/codetower/commit/aa0cdb83cd843bba70197e596706cc320fdf5260
- [ ] node-tree

**Comment by huming0618** [comment]
## Log
https://github.com/huming0618/codetower/commit/1e02c4355b00d99a12def9756050b14d00879a1d
added the "editable" property

## To-Do
- [ ] NoteTree - Add New / Update
  - [ ] Create DB
  - [ ] Server API 
- [ ] Save Data

**Comment by huming0618** [comment]
## Log
https://github.com/huming0618/codetower/commit/ec8823fb88cc1ae19655eb5dd7e7e67957973e7a
Add the NoteView on the right with editable items

**Comment by huming0618** [comment]
## Log
https://github.com/huming0618/codetower/commit/defb2ccdc4a7f2ebfa9e76125021dab803cc4485
import the material css library for Vue: http://vuematerial.io/#/
